// STEPS FOR HOMEWORK 

// EACH CLASS WILL HAVE THE FOLLOWING PROPERTIES AND METHODS:
// 1. Name
// 2. ID
// 3. Email
// 4. getName() method
// 5. getId() method
// 6. getEmail() method
// 7. getRole() method (returns role)

// MANAGER CLASS EXTENDS EMPLOYEE AND WILL ALSO NEED:
// 1. officeNumber
// 2. getRole() method (returns role(Manager) and overrides Employee)

// ENGINEER CLASS EXTENDS EMPLOYEE AND WILL ALSO NEED:
// 1. GitHub username
// 2. getGithub() method
// 3. getRole() method (returns role(Engineer) and overrides Employee)

// INTERN CLASS EXTENDS EMPLOYEE AND WILL ALSO NEED:
// 1. School
// 2. getSchool() method
// 3. getRole() method (returns role(Intern) and overrides Employee)

// CREATE A WALKTHROUGH VIDEO THAT INCLUDES:
// Demonstrates functionality
// Shows all 4 tests pass from the command line
// How the user invokes the application from the command line (node index.js)
// How the user enters responses to all the prompts 
// Shows the generated HTML file that matches user input

// MUST SUBMIT:
// 1. Link to walkthrough video
// 2. Github repository url
// 3. Sample HTML file generated by application
